# Generated by Django 4.0.4 on 2022-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_snippet_updated_alter_bank_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientfinancehistory',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clientfinancehistory',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passportperson',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='passportperson',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecredit',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecredit',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='status_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='status_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passportperson',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
